### ISSUE TITLE
Video rendering issue with GVRWebView in Android Studio

### ISSUE THREAD

**Issue by Maqsood007** [gearvrf/GearVRf-Demos#335] opened 2016-09-28 05:54 UTC
I am developing an application for Samsung GeerVR using GeerVR API's and i am trying to embed youtube video in GVRWebView but it just play sound and player look black.

` String frameVideo = "<html><body>Video From YouTube<br><iframe width=\"420\" height=\"315\" src=\"https://www.youtube.com/embed/47yJ2XCRLZs\" frameborder=\"0\" allowfullscreen></iframe></body></html>";

```
GVRWebView displayYoutubeVideo = new GVRWebView(this);
displayYoutubeVideo.setWebViewClient(new WebViewClient() {
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        return false;
    }
});
WebSettings webSettings = displayYoutubeVideo.getSettings();
webSettings.setJavaScriptEnabled(true);
displayYoutubeVideo.loadData(frameVideo, "text/html", "utf-8");`
```

Question: i check this video with Android WebView but it works fine on android native application but this video just not show up in GeerVR application.

**Comment by deepakrawat22** [comment] 2016-09-28 21:05
@parthmehta209 Could you help with this issue. As far I remember you created an app that played videos from reddit.

**Comment by Maqsood007** [comment] 2016-09-29 05:39
Sir,
 I need your help as soon as possible. i will be thankful to you.

**Comment by parthmehta209** [comment] 2016-09-29 07:18
@Maqsood007, I will try and reproduce this issue and investigate it further. Meanwhile you can try this solution which I have had success with in the past. 
You can use a GVRViewSceneObject. The GVRViewSceneObject accepts a frameLayout which can be inflated with a layout containing an Android WebView. 
You can find an example of using the GVRViewSceneObject in here: 
https://github.com/gearvrf/GearVRf-Demos/tree/master/gvr-events

Below is a sample usage of the webview embedded in the GVRViewSceneObject: 
1. Link to a class using the GVRViewSceneObject+WebView: https://github.com/parthmehta209/GearVRf-Demos/blob/redditViewer/gvr-reddit-viewer/app/src/main/java/org/gearvrf/io/sceneeditor/RedditWebView.java

2. LInk to layout file that embeds a webview used in the GVRViewSceneObject: https://github.com/parthmehta209/GearVRf-Demos/blob/redditViewer/gvr-reddit-viewer/app/src/main/res/layout/web_view_layout.xml

**Comment by Maqsood007** [comment] 2016-10-05 06:50
Sir, any progress on playing video using GeerVR API's . Still i am unable to play.

**Comment by Maqsood007** [comment] 2016-10-05 12:59
Sir i need to know that is it possible to render youtube video on Web view in GVR Application. because i test lot of ways to do but each implementation just play sound and unable to show video frames. ????

**Comment by ragner** [comment] 2016-10-06 16:06
Hi @Maqsood007,
do you have any sample with Android WebView working on native android to share with us?

I will try help you,
thank you.

**Comment by ragner** [comment] 2016-10-06 19:13
Ok,
I have got the same issue. We need a fix to it.

**Comment by liaxim** [comment] 2016-10-06 19:17
@ragner Have you tried setting useProtectedFramebuffer to true in gvr.xml? Any difference?

**Comment by ragner** [comment] 2016-10-06 19:27
@liaxim Yes, I have tried. No difference.
I think there is some internal implementation in WebView to improve video rendering 
and we are missing it. I am checking

**Comment by ragner** [comment] 2016-10-06 23:40
Ok,
at GVRWebView if I just do 
`public void draw(Canvas canvas)
{ super.draw(canvas);}
`
the video plays normally.  So the issue looks related to the Canvas that we are using.

**Comment by Maqsood007** [comment] 2016-10-07 07:46
yes sure , let me try your solution and i will also share also my sample
code...

**Comment by Maqsood007** [comment] 2016-10-07 11:42
@deepakrawat22 @parthmehta209 @ragner @liaxim @dankex 
Here i made a new repository for GVRWebView that contains sample code about what i already did.So please contribute there so we can fix this issue.. Thank you

**Comment by ragner** [comment] 2016-10-07 23:12
Ok,
Unfortunately I didn't find any solution to this issue.
I am not sure if is possible to fix it.


http://stackoverflow.com/questions/19273437/android-draw-youtube-video-on-surfacetexture

**Comment by liaxim** [comment] 2016-11-01 18:33
@Maqsood007 The issue is pretty old. Have you been able to do get the WebView rendering to a SurfaceTexture when GVRF is not involved? Planning to close this in a few days.

**Closed** 2016-11-07 17:25 UTC
Labels: question

**Comment by xiongjianxjtu** [comment] 2016-11-14 06:29
@Maqsood007  hi,have you solved this problem?I have the same trouble with  you.if you have a solution,could please share it with me

**Comment by Maqsood007** [comment] 2016-11-14 17:35
No,  i was unable to find a suitable solution, still it playing just sound
 and video frames are not showing up.

**Comment by shaishav-mtech** [comment] 2017-02-08 06:58
I have got it working! check [this](https://github.com/Samsung/GearVRf/issues/1033#issuecomment-278244683)
