### ISSUE TITLE
Lighting went wrong when 2 x3d files are loaded

### ISSUE THREAD

**Issue by xcaostagit** [gearvrf/GearVRf-Demos#422] opened 2017-03-17 23:07 UTC
I loaded "teapotandtorus.x3d" and "cylindersandplanes.x3d" together and noticed some weird lighting effects. Attached is the modified SampleMain.java in project gvr-simplesample. You need to copy all asset files from gvr-x3ddemo into the assets folder of gvr-simplesample.
[SampleMain.zip](https://github.com/gearvrf/GearVRf-Demos/files/851958/SampleMain.zip)

**Comment by mwitchwilliams** [comment] 2017-03-20 22:13
"cylindersandplanes.x3d" has one DirectionalLight.  "teapotandtorus.x3d" has no lights.
Would you happen to have screen shot(s) of what you are seeing?
It would be interesting to use the X3D Inline node as well to load "teapotandtorus.x3d" from within "cylindersandplanes.x3d" by adding at the end (before the </Scene> node):
<Inline url="teapotandtorus.x3d"/>

**Comment by NolaDonato** [comment] 2017-03-20 23:51
The problem is that cylindersandplanes.x3d contains a light. When the light is included, GearVRF uses lighting shaders. The X3D importer is not doing the right thing with the "shininess" parameter. This is 0-1 in X3D but GearVRF requires a specular power > 1. The X3D importer needs to correctly map shininess to GearVRF specular power.

**Comment by liaxim** [comment] 2017-03-22 17:55
Fixed by https://github.com/Samsung/GearVRf/pull/1103.

**Closed by liaxim** 2017-03-22 17:55 UTC
Labels: bug
