### ISSUE TITLE
gvr-Vuforia teapot slide issue.

### ISSUE THREAD

**Issue by PsycoTodd** [gearvrf/GearVRf-Demos#46] opened 2016-03-10 08:08 UTC
Hello,

Thank you for the nice demo! However, I notice that in the gvr-Vuforia demo, when the user hold the image target and slightly shift the HMD, the virtual teapot shifts more which makes it not relatively fixed at the detected position. If the user move the card away from the camera, the teapot disappear.

For the disappearance issue, It is possible that the teapot is moved behind the quad of video, or just out of the Gear VR culling Frustum. In the original Vuforia VR demo, when drawing the background video quad, depth test is disabled so no matter how the object which is drawn after the video quad moves in z direction, it will not be hide. So my question is: how can we increase the Z-Far plane for larger culling Frustum, and how can we disable the depth test for the screen object to make sure that the 3D things drawn are all above the video?

And for the 3D object slightly shift during moving the image target or move the head, is that possible due to the view port difference? 

Hope to hear from you soon!

**Comment by liaxim** [comment] 2016-03-10 15:55
See GVRSceneObject.getRenderData().setDepthTest and GVRScene.getMainCameraRig().setFarClippingDistance.

**Comment by PsycoTodd** [comment] 2016-03-11 00:54
Hello,

I notice that the translation and scale of the virtual model is the major issue of the current demo.

Scaling: I notice that in the code an empirical UV coordinate is used to draw the background video, this UV has effect of zoom in. However, the original scale obtained from Vuforia does not take this into account so it may lead to the virtual object looks smaller relative to the background video.

Translation: aka the sliding issue. the object does not move to the center as the image. If I draw a cube at the center of the Vuforia tracking target, when I move the image target and watch the virtual object drawn in Gear VR, the virtual object won't keep at the center of the image target at all. It is like that the video is projected by the vuforia matrix and then projected by the Gear VR system, while in the demo, the virtual teapot is manipulated by vuforia model view but project only by gear VR matrix.
Not quiet sure the explanation about this issue but hope some one can share their opinion on this.

Todd

**Comment by PsycoTodd** [comment] 2016-03-11 04:34
OK, I think the the root of evil is the empirical UV coordinate system, it makes the translation and scaling factor of the vuforiaMVMatrix not aligned with the rendered result. Depending on the UV sub sample region, the vuforiaMVMatrix need to be updated accordingly.

Hope it helps!

**Comment by liaxim** [comment] 2016-03-15 22:39
@PsycoTodd We will be looking at this but since the problem is with the sample itself it may take a while. Free free to open a pull request if you have a fix in mind.

**Comment by PsycoTodd** [comment] 2016-03-16 17:31
@liaxim, Sure I will try to add the change to the demo code during weekend and make a pull request. Hope it can helps a little bit.

**Comment by liaxim** [comment] 2016-03-16 19:02
Thank you in advance.

**Comment by PsycoTodd** [comment] 2016-04-22 23:19
Hello, I originally try to adjust the model matrix and make the alignment kinda work. However, without touching the code these days I suddenly found that the object I displayed shrink... I have not touch my code and I don't update the GearVR framework. I feel that the Oculus Gear VR may update with some new things... Now I need to dig into it again to see how to adjust the matrix... 

Just want to see if you encounter similar things. Basically, if you run the demo in the phone with a updated Gear VR services it looks different to the previous one.

**Comment by liaxim** [comment] 2016-04-26 20:27
@PsycoTodd Not to my knowledge. I have recently ran the sample on an S7 with up-to-date Oculus services and it looked the same to me.

**Comment by PsycoTodd** [comment] 2016-04-26 23:17
@liaxim  I think the problem is that we cannot run a so called previous version any more. Even without update, the old demo may run differently due to the updated Oculus services right? I am looking into this issue and find at least that the scale is shrink by twice. I may run the teapot demo again to confirm the issue. 

Thank you for reply!

**Comment by PsycoTodd** [comment] 2016-04-26 23:49
@liaxim As we can see here, if the target is far away, we can see the teapot will move around while the camera movies, which is not right since the the teapot should be still relative to the image target.
![screenshot_20160426-164157](https://cloud.githubusercontent.com/assets/8716430/14837601/b280bf1e-0bce-11e6-9bf1-3679a1d5f974.png)

**Comment by teresa-mao** [comment] 2016-04-27 01:19
@PsycoTodd I'm looking into this issue now, will have an update soon.

**Comment by PsycoTodd** [comment] 2016-04-27 01:31
@liaxim @teresa-mao  Thanks Teresa for looking into this. I kinda feel excited to see what is the trick that can make this work. Thank you!

Originally I fixed this issue by times the vuforia matix's 12 and 13 elements (x trans and y trans) by 1/0.62 and 1/0.7 respectively since I notice that the see-through texture actually sub-sampled the UV space of the camera stream feed. That might be a way to go.

**Comment by PsycoTodd** [comment] 2016-05-26 18:43
Hello @teresa-mao , Hope you are doing well. Do we have a explanation about this issue yet?

Thank you.

**Comment by liaxim** [comment] 2016-06-03 21:00
@PsycoTodd We still have no good solution.

**Comment by liaxim** [comment] 2016-07-05 15:32
@PsycoTodd Thanks to @deepakrawat22 we finally have a good solution for the problem. Please check out https://github.com/gearvrf/GearVRf-Demos/pull/201 and let us know what you think. Thank you.

**Comment by PsycoTodd** [comment] 2016-07-05 19:00
Dear Guys
Thank you for looking into this. Please merge it into the master so I can
pull the updates.

Thank you again.

**Comment by liaxim** [comment] 2016-07-06 14:43
@PsycoTodd You could try this ahead of time if you'd like by pulling the change:

``
git pull https://github.com/deepakrawat22/GearVRf-Demos.git vu
``

**Comment by PsycoTodd** [comment] 2016-07-07 06:58
Hello guys

Notice that seems you have update the demo to android studio from Eclipse.
I believe it may need a specific set up to run gvr-vuforia now. So it may
take me a while since my original test bed is in eclipse.

BTW, I notice all the files changed in Deepak branch is from gvr-vuforia. I
may just try to update the corresponding files in my current project and
see if the 3D object stops slide.

Todd

**Comment by liaxim** [comment] 2016-07-07 14:28
You can still use Eclipse. When importing just point to the demo's directory and Eclipse will find the project file.

**Comment by liaxim** [comment] 2016-07-14 16:17
Pull request has been merged. @PsycoTodd you could try it out now.

**Comment by PsycoTodd** [comment] 2016-07-14 16:42
Thank you.

**Comment by liaxim** [comment] 2016-07-15 14:32
Since we believe we finally have addressed the root cause I am planning to close this issue soon.

**Comment by PsycoTodd** [comment] 2016-07-15 15:15
I agree. Thanks everyone for spending time on this.

**Closed** 2016-07-15 15:50 UTC
Labels: bug
