### ISSUE TITLE
360 Video not playing if we include  useGazeCursorController="true" in gvr.xml

### ISSUE THREAD

**Issue by Malikkhoja** [gearvrf/GearVRf-Demos#438] opened 2017-04-13 12:50 UTC
Hi @liaxim,

I am new to VR development. I am making a very simple application with 2 scenes and 1 video player. Once i click on a video from the list the video is not visible but I can hear the sound. The only point where it works is when I remove  useGazeCursorController="true" from gvr.xml but then it doenst draw the cursor on my list screen.

Can anyone help please?

Thanks in advance.

**Comment by senseearth** [comment] 2017-04-13 21:15
Hi @Malikkhoja 

Could you attach here a minimal sample with code so we can try?

Thanks

**Comment by bohuang3d** [comment] 2017-04-13 21:16
Hi @Malikkhoja 

Could you attach here a minimal sample with code we can try?

Thanks

**Comment by liaxim** [comment] 2017-05-01 14:32
@Malikkhoja Tried it but could not reproduce. Closing for now. Let us know if you can give us more information. Thanks.

**Closed by liaxim** 2017-05-01 14:32 UTC
Labels: question
